# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Joyce Liu
tagline:          'Seattle Software Engineer'
description:      'Software engineer and foreign language enthusiast living in Seattle'
url:              liujoycec.github.io
baseurl:          /

author:
  name:           'Joyce Liu'
  url:            liujoycec.github.io

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/liujoycec/liujoycec.github.io
