# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Joyce Liu
tagline:          'Seattle Software Developer'
description:      'Software developer, math geek, and foreign language enthusiast living in Seattle'
url:              liujoycec.github.io
baseurl:          /
picurl:           https://avatars2.githubusercontent.com/u/12114318?v=3&s=460

author:
  name:           'Joyce Liu'
  url:            liujoycec.github.io

paginate:         5

github:           https://github.com/liujoycec

codepen:          http://codepen.io/LiuJoyceC